name = "kimpure/asciitable"
version = "0.3.5"
description = "try outputting in ascii"
authors = ["kimpure (sunwoo)"]
repository = "https://github.com/kimpure/asciitable-luau"
license = "MIT"
includes = [ "src/**", "pesde.toml", "LICENCE.md", "README.md" ]

[target]
environment = "luau"
lib = "src/lib.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.1"

[dev_dependencies]
darklua = { name = "pesde/darklua", version = "^0.17.1", target = "lune" }
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.30", target = "lune" }
